// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
    String N = args[0];
	int n = Integer.parseInt(N);	
	int countBig = 0;
	int countSmall = 0;
	for (int i=0; i<n; i++) {
		 double TestRandom = (double) Math.random();
		if (TestRandom > 0.5) {
			countBig++;
		} else {
			countSmall++;
		}
	}


	System.out.println("> 0.5: " + countBig);
	System.out.println("<= 0.5: " + countSmall);
	System.out.println("Ratio: " + (double) countBig / countSmall);
  }
}
